### PR TITLE
bug fix -- fix for accessing APIError.code throws TypeError

### PR DESCRIPTION
**Pull request by mikenester**
Fix for https://github.com/alpacahq/alpaca-py/issues/166

### CODE REVIEW

**Comment by mikenester** [comment]
@haxdds Could I get a review on this guy whenever you get a chance? 🙇

**Comment by haxdds** [comment]
@mikenester I'm taking a look thanks

**Comment by mikenester** [comment]
bump

**Comment by mikenester** [comment]
@haxdds Any chance to look at this yet? also are there docs on the release schedule?

**Review by haxdds — APPROVED** [review]
This looks good thank you for the contribution

**Comment by haxdds** [comment]
> @haxdds Any chance to look at this yet? also are there docs on the release schedule?

Currently, there isn't a release schedule

**Pull request merged**
