### PR TITLE
fix: optional fields in FailedClosePositionDetails

### PR DESCRIPTION
**Pull request by alessiocastrica**

### CODE REVIEW

**Review by AlexandrosKyriakakis — COMMENTED** [review]
@alessiocastrica  would mind adding a description that explains the problem and the solution? I got a bit confused.

**Comment by alessiocastrica** [comment]
@AlexandrosKyriakakis sure, basically when we get a response on a failed order without additional fields (only including error code and message) pydantic validation for `FailedClosePositionDetails` will fail as those fields were not marked as optional. We can huddle about it if you want more context. 
image

**Comment by alessiocastrica** [comment]
and a minor fix I added was the fact that `cancel_orders` should be optional in the method as it's an optional query parameter

**Review by AlexandrosKyriakakis — APPROVED** [review]
LGTM

**Review by hiohiohio — APPROVED** [review]

**Pull request merged**
